"""Upgrade operation

Revision ID: 9d4967367da4
Revises: af3d999591ca
Create Date: 2024-06-13 16:16:02.250289

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9d4967367da4'
down_revision: Union[str, None] = 'af3d999591ca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('operations', 'instrument_type',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('operations', 'instrument_type',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
